// <auto-generated />
using System;
using CityChecker.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CityChecker.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260719200835_PointNotesReplaceDistrict")]
    partial class PointNotesReplaceDistrict
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CityChecker.Api.Data.Entities.AppUser", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CityChecker.Api.Data.Entities.Building", b =>
                {
                    b.Property<Guid>("BuildingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AddressLine")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<Guid>("CityId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DistrictId")
                        .HasColumnType("uuid");

                    b.Property<double>("Lat")
                        .HasColumnType("double precision");

                    b.Property<double>("Lon")
                        .HasColumnType("double precision");

                    b.HasKey("BuildingId");

                    b.HasIndex("DistrictId");

                    b.HasIndex("CityId", "AddressLine");

                    b.HasIndex("Lat", "Lon");

                    b.ToTable("Buildings");
                });

            modelBuilder.Entity("CityChecker.Api.Data.Entities.City", b =>
                {
                    b.Property<Guid>("CityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("CenterLat")
                        .HasColumnType("double precision");

                    b.Property<double>("CenterLon")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("OfficialCode")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Voivodeship")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("CityId");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("CityChecker.Api.Data.Entities.DecisionProfile", b =>
                {
                    b.Property<Guid>("ProfileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("WeightComfort")
                        .HasColumnType("integer");

                    b.Property<int>("WeightCommute")
                        .HasColumnType("integer");

                    b.Property<int>("WeightGreen")
                        .HasColumnType("integer");

                    b.Property<int>("WeightPrice")
                        .HasColumnType("integer");

                    b.Property<int>("WeightQuiet")
                        .HasColumnType("integer");

                    b.HasKey("ProfileId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("DecisionProfiles");
                });

            modelBuilder.Entity("CityChecker.Api.Data.Entities.District", b =>
                {
                    b.Property<Guid>("DistrictId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double?>("AreaKm2")
                        .HasColumnType("double precision");

                    b.Property<Guid>("CityId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<MultiPolygon>("Geom")
                        .IsRequired()
                        .HasColumnType("geometry(MultiPolygon, 4326)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("OfficialCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("SourceName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("DistrictId");

                    b.HasIndex("Geom");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Geom"), "GIST");

                    b.HasIndex("CityId", "Name");

                    b.ToTable("Districts");
                });

            modelBuilder.Entity("CityChecker.Api.Data.Entities.DistrictImportRaw", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ExtraJson")
                        .HasColumnType("text");

                    b.Property<DateTime>("ImportedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Osiedla")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PunktyGraniczne")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.ToTable("districts_import_raw", (string)null);
                });

            modelBuilder.Entity("CityChecker.Api.Data.Entities.DistrictPick", b =>
                {
                    b.Property<Guid>("PickId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DistrictId")
                        .HasColumnType("uuid");

                    b.Property<double?>("NearestHighwayKm")
                        .HasColumnType("double precision");

                    b.Property<int?>("ParkCount")
                        .HasColumnType("integer");

                    b.Property<int?>("PharmacyCount")
                        .HasColumnType("integer");

                    b.Property<int?>("QuietScore")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ReminderAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReminderNote")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("RiskNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int?>("SchoolCount")
                        .HasColumnType("integer");

                    b.Property<int?>("ShopCount")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int?>("TransitStopCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("VetoReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("PickId");

                    b.HasIndex("DistrictId");

                    b.HasIndex("UserId", "DistrictId")
                        .IsUnique();

                    b.ToTable("DistrictPicks");
                });

            modelBuilder.Entity("CityChecker.Api.Data.Entities.DistrictVisit", b =>
                {
                    b.Property<Guid>("VisitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("Daylight")
                        .HasColumnType("integer");

                    b.Property<Guid>("DistrictId")
                        .HasColumnType("uuid");

                    b.Property<int?>("DogWalk")
                        .HasColumnType("integer");

                    b.Property<int?>("EveningFeel")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<int?>("SaturdayLife")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("VisitedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("WinterFeel")
                        .HasColumnType("integer");

                    b.HasKey("VisitId");

                    b.HasIndex("DistrictId");

                    b.HasIndex("UserId", "DistrictId");

                    b.ToTable("DistrictVisits");
                });

            modelBuilder.Entity("CityChecker.Api.Data.Entities.HousingOffer", b =>
                {
                    b.Property<Guid>("OfferId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BuildingId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CityId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("Czynsz")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Deposit")
                        .HasColumnType("numeric");

                    b.Property<Guid?>("DistrictId")
                        .HasColumnType("uuid");

                    b.Property<int?>("Floor")
                        .HasColumnType("integer");

                    b.Property<bool?>("Furnished")
                        .HasColumnType("boolean");

                    b.Property<bool?>("HasKsiega")
                        .HasColumnType("boolean");

                    b.Property<bool?>("HasSluzebnosc")
                        .HasColumnType("boolean");

                    b.Property<bool?>("HasSpoldzielniaDebt")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("Internet")
                        .HasColumnType("numeric");

                    b.Property<bool>("IsFinalist")
                        .HasColumnType("boolean");

                    b.Property<string>("KillerFlaw")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("LandlordNotes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<double>("Lat")
                        .HasColumnType("double precision");

                    b.Property<double>("Lon")
                        .HasColumnType("double precision");

                    b.Property<decimal?>("Media")
                        .HasColumnType("numeric");

                    b.Property<int>("Mode")
                        .HasColumnType("integer");

                    b.Property<int?>("NoticeDays")
                        .HasColumnType("integer");

                    b.Property<decimal?>("ParkingFee")
                        .HasColumnType("numeric");

                    b.Property<string>("PhotoUrls")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<decimal?>("Price")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("PricePerSqm")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("ReminderAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReminderNote")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<decimal?>("RenovationBudget")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("RentOrMortgage")
                        .HasColumnType("numeric");

                    b.Property<int?>("Rooms")
                        .HasColumnType("integer");

                    b.Property<int?>("ScoreBalcony")
                        .HasColumnType("integer");

                    b.Property<int?>("ScoreCellar")
                        .HasColumnType("integer");

                    b.Property<int?>("ScoreCondition")
                        .HasColumnType("integer");

                    b.Property<int?>("ScoreElevator")
                        .HasColumnType("integer");

                    b.Property<int?>("ScoreHeating")
                        .HasColumnType("integer");

                    b.Property<int?>("ScoreLayout")
                        .HasColumnType("integer");

                    b.Property<int?>("ScoreLight")
                        .HasColumnType("integer");

                    b.Property<int?>("ScoreNeighbors")
                        .HasColumnType("integer");

                    b.Property<int?>("ScoreParking")
                        .HasColumnType("integer");

                    b.Property<int?>("ScorePrice")
                        .HasColumnType("integer");

                    b.Property<double?>("Sqm")
                        .HasColumnType("double precision");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Url")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("VoiceNoteUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int?>("YearBuilt")
                        .HasColumnType("integer");

                    b.HasKey("OfferId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "IsFinalist");

                    b.ToTable("HousingOffers");
                });

            modelBuilder.Entity("CityChecker.Api.Data.Entities.MapAnchor", b =>
                {
                    b.Property<Guid>("AnchorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<double>("Lat")
                        .HasColumnType("double precision");

                    b.Property<double>("Lon")
                        .HasColumnType("double precision");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("AnchorId");

                    b.HasIndex("UserId");

                    b.ToTable("MapAnchors");
                });

            modelBuilder.Entity("CityChecker.Api.Data.Entities.Note", b =>
                {
                    b.Property<Guid>("NoteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AuthorGoogleId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("Lat")
                        .HasColumnType("double precision");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<double?>("Lon")
                        .HasColumnType("double precision");

                    b.Property<int?>("RadiusMeters")
                        .HasColumnType("integer");

                    b.Property<int?>("ScoreNature")
                        .HasColumnType("integer");

                    b.Property<int>("ScoreOverall")
                        .HasColumnType("integer");

                    b.Property<int?>("ScoreSafety")
                        .HasColumnType("integer");

                    b.Property<int?>("ScoreShops")
                        .HasColumnType("integer");

                    b.Property<int?>("ScoreTransport")
                        .HasColumnType("integer");

                    b.Property<Guid?>("TargetBuildingId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TargetCityId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TargetDistrictId")
                        .HasColumnType("uuid");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("NoteId");

                    b.HasIndex("AuthorGoogleId");

                    b.HasIndex("TargetBuildingId");

                    b.HasIndex("TargetDistrictId");

                    b.HasIndex("Lat", "Lon");

                    b.HasIndex("TargetCityId", "Level");

                    b.ToTable("Notes");
                });

            modelBuilder.Entity("CityChecker.Api.Data.Entities.Building", b =>
                {
                    b.HasOne("CityChecker.Api.Data.Entities.City", "City")
                        .WithMany("Buildings")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CityChecker.Api.Data.Entities.District", "District")
                        .WithMany("Buildings")
                        .HasForeignKey("DistrictId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("City");

                    b.Navigation("District");
                });

            modelBuilder.Entity("CityChecker.Api.Data.Entities.District", b =>
                {
                    b.HasOne("CityChecker.Api.Data.Entities.City", "City")
                        .WithMany("Districts")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("CityChecker.Api.Data.Entities.DistrictPick", b =>
                {
                    b.HasOne("CityChecker.Api.Data.Entities.District", "District")
                        .WithMany()
                        .HasForeignKey("DistrictId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("District");
                });

            modelBuilder.Entity("CityChecker.Api.Data.Entities.DistrictVisit", b =>
                {
                    b.HasOne("CityChecker.Api.Data.Entities.District", "District")
                        .WithMany()
                        .HasForeignKey("DistrictId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("District");
                });

            modelBuilder.Entity("CityChecker.Api.Data.Entities.Note", b =>
                {
                    b.HasOne("CityChecker.Api.Data.Entities.Building", "TargetBuilding")
                        .WithMany()
                        .HasForeignKey("TargetBuildingId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CityChecker.Api.Data.Entities.City", "TargetCity")
                        .WithMany()
                        .HasForeignKey("TargetCityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CityChecker.Api.Data.Entities.District", "TargetDistrict")
                        .WithMany()
                        .HasForeignKey("TargetDistrictId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("TargetBuilding");

                    b.Navigation("TargetCity");

                    b.Navigation("TargetDistrict");
                });

            modelBuilder.Entity("CityChecker.Api.Data.Entities.City", b =>
                {
                    b.Navigation("Buildings");

                    b.Navigation("Districts");
                });

            modelBuilder.Entity("CityChecker.Api.Data.Entities.District", b =>
                {
                    b.Navigation("Buildings");
                });
#pragma warning restore 612, 618
        }
    }
}
