// <auto-generated />
using System;
using CityChecker.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CityChecker.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CityChecker.Api.Data.Entities.Building", b =>
                {
                    b.Property<Guid>("BuildingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AddressLine")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<Guid>("CityId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DistrictId")
                        .HasColumnType("uuid");

                    b.Property<double>("Lat")
                        .HasColumnType("double precision");

                    b.Property<double>("Lon")
                        .HasColumnType("double precision");

                    b.HasKey("BuildingId");

                    b.HasIndex("DistrictId");

                    b.HasIndex("CityId", "AddressLine");

                    b.HasIndex("Lat", "Lon");

                    b.ToTable("Buildings");
                });

            modelBuilder.Entity("CityChecker.Api.Data.Entities.City", b =>
                {
                    b.Property<Guid>("CityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("CenterLat")
                        .HasColumnType("double precision");

                    b.Property<double>("CenterLon")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("OfficialCode")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Voivodeship")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("CityId");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("CityChecker.Api.Data.Entities.District", b =>
                {
                    b.Property<Guid>("DistrictId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double?>("AreaKm2")
                        .HasColumnType("double precision");

                    b.Property<Guid>("CityId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<MultiPolygon>("Geom")
                        .IsRequired()
                        .HasColumnType("geometry(MultiPolygon, 4326)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("OfficialCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("SourceName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("DistrictId");

                    b.HasIndex("Geom");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Geom"), "GIST");

                    b.HasIndex("CityId", "Name");

                    b.ToTable("Districts");
                });

            modelBuilder.Entity("CityChecker.Api.Data.Entities.DistrictImportRaw", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ExtraJson")
                        .HasColumnType("text");

                    b.Property<DateTime>("ImportedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Osiedla")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PunktyGraniczne")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.ToTable("districts_import_raw", (string)null);
                });

            modelBuilder.Entity("CityChecker.Api.Data.Entities.Note", b =>
                {
                    b.Property<Guid>("NoteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AuthorGoogleId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<int?>("ScoreNature")
                        .HasColumnType("integer");

                    b.Property<int>("ScoreOverall")
                        .HasColumnType("integer");

                    b.Property<int?>("ScoreSafety")
                        .HasColumnType("integer");

                    b.Property<int?>("ScoreShops")
                        .HasColumnType("integer");

                    b.Property<int?>("ScoreTransport")
                        .HasColumnType("integer");

                    b.Property<Guid?>("TargetBuildingId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TargetCityId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TargetDistrictId")
                        .HasColumnType("uuid");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("NoteId");

                    b.HasIndex("AuthorGoogleId");

                    b.HasIndex("TargetBuildingId");

                    b.HasIndex("TargetDistrictId");

                    b.HasIndex("TargetCityId", "Level");

                    b.ToTable("Notes");
                });

            modelBuilder.Entity("CityChecker.Api.Data.Entities.Building", b =>
                {
                    b.HasOne("CityChecker.Api.Data.Entities.City", "City")
                        .WithMany("Buildings")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CityChecker.Api.Data.Entities.District", "District")
                        .WithMany("Buildings")
                        .HasForeignKey("DistrictId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("City");

                    b.Navigation("District");
                });

            modelBuilder.Entity("CityChecker.Api.Data.Entities.District", b =>
                {
                    b.HasOne("CityChecker.Api.Data.Entities.City", "City")
                        .WithMany("Districts")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("CityChecker.Api.Data.Entities.Note", b =>
                {
                    b.HasOne("CityChecker.Api.Data.Entities.Building", "TargetBuilding")
                        .WithMany()
                        .HasForeignKey("TargetBuildingId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CityChecker.Api.Data.Entities.City", "TargetCity")
                        .WithMany()
                        .HasForeignKey("TargetCityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CityChecker.Api.Data.Entities.District", "TargetDistrict")
                        .WithMany()
                        .HasForeignKey("TargetDistrictId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("TargetBuilding");

                    b.Navigation("TargetCity");

                    b.Navigation("TargetDistrict");
                });

            modelBuilder.Entity("CityChecker.Api.Data.Entities.City", b =>
                {
                    b.Navigation("Buildings");

                    b.Navigation("Districts");
                });

            modelBuilder.Entity("CityChecker.Api.Data.Entities.District", b =>
                {
                    b.Navigation("Buildings");
                });
#pragma warning restore 612, 618
        }
    }
}
